AccountID: "963662274920"
App: "HalappAccount"
Environment: DEVELOPMENT
Region: eu-central-1
SESFromEmail: no-reply@halapp.io
SESCCEmail: furkan.ozdeslik@gmail.com
S3OrganizationEnrollmentEmailTemplate: organization-enrollment.ejs
# comes from HalApp-Auth 
# comes from HalApp-Auth 


ShouldCreateDynamoAccountDB: "false"
AccountDBName: HalAccount

UserPoolID: eu-central-1_xGVP5Phra
UserPoolClientID: 4fq0oja4v9fir2n3uh8mqbi2h0

AUTH_SNSUserCreatedTopic: "AUTH_UserCreatedTopic"
AUTH_SNSUserJoinedOrganizationTopic: "AUTH_UserJoinedOrganizationTopic"
SNSOrganizationCreatedTopic: "ACCOUNT_OrganizationCreatedTopic"
ORDER_SNSOrderTopic: "ORDER_OrderTopic"


AUTH_SQSOrganizationCreatedQueue: "AUTH_OrganizationCreatedQueue"
SQSUserCreatedQueue: "ACCOUNT_UserCreatedQueue"
SQSUserJoinedOrganizationQueue: "ACCOUNT_UserJoinedOrganizationQueue"

